# Generated by Django 3.0.7 on 2021-02-16 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20210216_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repositories.Repository'),
        ),
    ]
